server:  
  port: 8888  
  
spring:  
  cloud:  
    config:  
      enabled: true  
      server:  
        svn:  
          uri: http://192.168.0.66/svn/cloudconfig/  
          username: chenhua  
          password: 123456  
        #git:  
        #  uri: https://github.com/pcf-guides/configuration-server-config-repo  
        default-label: config  
  profiles:  
    active: subversion  
  
logging:  
  levels:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE  
    org.springframework.cloud.config.server: DEBUG 
    