DROP TABLE IF EXISTS `T_CLIENT`;
CREATE TABLE IF NOT EXISTS `T_CLIENT` (
   `ID` bigint(20) NOT NULL AUTO_INCREMENT,
   `CLIENT_ID` varchar(128) NOT NULL,
   `CLIENT_SECRET` varchar(256) DEFAULT NULL,
   `RESOURCE_IDS` varchar(256) DEFAULT NULL,
   `SCOPE` varchar(256) DEFAULT NULL,
   `AUTHORITIES` varchar(256) DEFAULT NULL,
   `AUTHORIZED_GRANT_TYPES` varchar(256) DEFAULT NULL,
   `ACCESS_TOKEN_VALIDITY` int(11) DEFAULT NULL,
   `REFRESH_TOKEN_VALIDITY` int(11) DEFAULT NULL,
   `AUTOAPPROVE` varchar(256) DEFAULT NULL,
   `WEB_SERVER_REDIRECT_URI` varchar(256) DEFAULT NULL,
   `ADDITIONAL_INFORMATION` varchar(4096) DEFAULT NULL,
   `CREATE_TIME` datetime DEFAULT NULL,
   `EXPIRE_TIME` datetime DEFAULT NULL,
   `DELETE_FLAG` int(1) DEFAULT NULL,
   PRIMARY KEY (`ID`),
   UNIQUE KEY `UNIQUE_CLIENT_ID` (`CLIENT_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `T_USER` (
   `ID` bigint(20) NOT NULL AUTO_INCREMENT,
   `USERNAME` varchar(100) DEFAULT NULL,
   `PASSWORD` varchar(255) DEFAULT NULL,
   `SALT` varchar(100) DEFAULT NULL,
   `CREATE_TIME` datetime DEFAULT NULL,
   `EXPIRE_TIME` datetime DEFAULT NULL,
   `DELETE_FLAG` int(1) DEFAULT NULL,
   `STATUS` int(11) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
 
 CREATE TABLE IF NOT EXISTS `T_ROLE` (
   `ID` bigint(20) NOT NULL AUTO_INCREMENT,
   `NAME` varchar(255) DEFAULT NULL,
   `IDENTITY` varchar(255) DEFAULT NULL,
   `DESCRIPTION` varchar(255) DEFAULT NULL,
   `DELETE_FLAG` int(1) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;
 
CREATE TABLE IF NOT EXISTS `T_USER_ROLE` (
   `ID` bigint(20) DEFAULT NULL,
   `USER_ID` bigint(20) NOT NULL,
   `ROLE_ID` bigint(20) NOT NULL,
   `PRIORITY` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`USER_ID`,`ROLE_ID`),
   KEY `ROLE_ID` (`ROLE_ID`),
   CONSTRAINT `T_USER_ROLE_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `T_USER` (`ID`),
   CONSTRAINT `T_USER_ROLE_ibfk_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `T_ROLE` (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 

