spring.profiles.active=development

spring.application.name=kafka-server

management.security.enabled=false

server.port=14000

eureka.instance.metadataMap.instanceId=${spring.application.name}:${random.value}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://eureka-server-1:10001/eureka,http://eureka-server-2:10002/eureka

kafka.consumer.zookeeper.connect=192.168.0.124:2181/kafka
kafka.consumer.servers=192.168.0.124:9092
kafka.consumer.enable.auto.commit=true
kafka.consumer.session.timeout=6000
kafka.consumer.auto.commit.interval=100
kafka.consumer.auto.offset.reset=latest
#kafka.consumer.topic=test
kafka.consumer.group.id=test-consumer-group
kafka.consumer.concurrency=10

kafka.producer.servers=192.168.0.124:9092
kafka.producer.retries=0
kafka.producer.batch.size=4096
kafka.producer.linger=1
kafka.producer.buffer.memory=40960

logging.config=classpath:logging/logback.xml

logging.level.org.springframework.web=INFO
logging.level.org.springboot.sample=TRACE